[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  REACT_APP_GRAPHQL_ENDPOINT = "https://little-alchemy-two-graphql.onrender.com/graphql"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200